name: faith_plus
description: "The Christian Faith App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  glass: ^2.0.0+2
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Image_fx_1.jpg
    - assets/images/Image_fx_4.jpg
    - assets/images/Image_fx_6.jpg
    - assets/images/teresa.jpg